### ISSUE TITLE
Meetup URL is out of date

### ISSUE THREAD

**Issue by HarlanH** [HarlanH/code-for-dc-edu#94]
Currently: http://www.meetup.com/cfabrigade/Washington-DC/880272/

Should be: http://www.meetup.com/Code-for-DC/

**Comment by ajschumacher** [comment]
wait, what? @HarlanH why did you make an issue instead of just changing it?

**Comment by HarlanH** [comment]
was running out the door and didn't want to forget! (also, I'd want to push
the results, which would take a few more minutes...)

On Sun, May 17, 2015 at 12:52 PM, Aaron Schumacher <notifications@github.com

**Comment by ajschumacher** [comment]
mmmkay

**Comment by ajschumacher** [comment]
:tennis:
